In [1]:
import tensorflow as tf

In [2]:
constant_node = tf.constant(3.0, dtype=tf.float32)

In [3]:
print(constant_node)

Tensor("Const:0", shape=(), dtype=float32)


In [6]:
print(constant_node.shape)

()


In [8]:
session = tf.Session()

In [9]:
print(session.run([constant_node]))

[3.0]


In [11]:
constant_node2 = tf.constant(4.0, dtype=tf.float32)

In [12]:
node3=tf.add(constant_node, constant_node)

In [13]:
session.run(node3)

6.0

In [14]:
a = tf.placeholder(tf.float32)

In [15]:
b = tf.placeholder(tf.float32)

In [16]:
adder = a+b

In [21]:
session.run(adder, {a:[3, 5], b:[5, 3]})

array([ 8.,  8.], dtype=float32)

In [23]:
multiplier = a * b

In [24]:
session.run(multiplier, {a:[3,5], b:[5,3]})

array([ 15.,  15.], dtype=float32)

In [26]:
rank_3_matrix = tf.ones([3,4,5])

In [27]:
print(rank_3_matrix)

Tensor("ones:0", shape=(3, 4, 5), dtype=float32)


In [28]:
matrixB = tf.reshape(rank_3_matrix, [6,10])

In [29]:
print(matrixB)

Tensor("Reshape:0", shape=(6, 10), dtype=float32)


In [30]:
session.run(rank_3_matrix)

array([[[ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.]],

       [[ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.]],

       [[ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.]]], dtype=float32)

In [31]:
session.run(matrixB)

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]], dtype=float32)

In [32]:
tf.Print(matrixB)

TypeError: Print() missing 1 required positional argument: 'data'